#!/bin/bash

# Is the model still running

time_step_b=-1
time_step_n=0

while [ $time_step_b -lt $time_step_n ]
do
sleep 300
time_step_b=$time_step_n
time_step_n=`cat time.step`
done

if [ $time_step_n -lt $2 ]
then
	echo 'Having to cancel!'
	scancel $1
fi
